# frozen_string_literal: true

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = '--require ./bonus_formatter.rb --format BonusFormatter'
end

# desc "Look for style guide offenses in your code"
# task :rubocop do
#   sh "rubocop --format simple || true"
# end

desc 'Launch tests for the item namespace only'
task :int_item do
  sh 'rspec -t item'
end

desc 'Launch tests for the user namespace only'
task :int_user do
  sh 'rspec -t user'
end

desc 'Launch tests for the order namespace only'
task :int_order do
  sh 'rspec -t _order'
end

task default: %i[spec]

task item: %i[int_item]

task user: %i[int_user]

task order: %i[int_order]
